apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python app that displays the time!!!
  annotations:
    github.com/project-slug: naughlan-creator/python-app-for-platforming
spec:
  type: service
  owner: development
  lifecycle: experimental
