name: ci

on:
  push:
    paths:
      - src/**
        .github/workflows/**
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: log into docker
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKEHUB_TOKEN }}
      
      - name: set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ env.SHORT_SHA }}
