name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: log into docker
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKEHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ GITHUB_SHA::6 }}
