name: cicd

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/**"
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: log into docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ env.SHORT_SHA }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Install ArgoCd
        shell: bash
        run: |
          # install argocd
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
          
      - name: Argocd app sync
        env:
          ARGO_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGO_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username "$ARGOCD_USERNAME" \
            --password "$ARGOCD_PASSWORD"
          argocd app sync python-app
